# Generated by Django 3.2.3 on 2021-07-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myplant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_name',
        ),
    ]
