# Generated by Django 3.2.3 on 2021-07-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplant', '0006_auto_20210715_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_photo',
            field=models.ImageField(default='d', upload_to='image/'),
        ),
    ]
