# Generated by Django 3.2.3 on 2021-07-23 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myplant', '0010_alter_posts_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date published'),
        ),
    ]
