# Generated by Django 3.2.3 on 2021-08-08 12:06

import bluetoothAdriuno.main
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myplant', '0012_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='humidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(default=bluetoothAdriuno.main.data1, editable=False, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_post', to='myplant.posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.CharField(max_length=1200),
        ),
    ]
