# Generated by Django 3.2.3 on 2021-08-08 12:24

import bluetoothAdriuno.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplant', '0013_auto_20210808_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidity',
            name='data',
            field=models.CharField(default=bluetoothAdriuno.main.data1, max_length=200, null=True),
        ),
    ]
