# Generated by Django 3.2.3 on 2021-08-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplant', '0015_alter_humidity_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidity',
            name='data',
            field=models.IntegerField(default=0),
        ),
    ]
