# Generated by Django 3.2.3 on 2021-08-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplant', '0016_alter_humidity_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='humidity',
        ),
        migrations.AddField(
            model_name='addplant',
            name='device',
            field=models.CharField(default='no devices in range', max_length=200),
        ),
    ]
