# Generated by Django 3.2.3 on 2021-08-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplant', '0017_auto_20210815_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumudityStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200)),
            ],
        ),
    ]
