# Generated by Django 3.2.3 on 2021-08-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myplant', '0018_humuditystat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='HumudityStat',
        ),
    ]
